// <auto-generated />
namespace Examino.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class secondmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201604041436539_second migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
